"""create soft prompts table

Revision ID: b2363fd8dd59
Revises: e1b2cec09880
Create Date: 2021-12-29 05:59:28.729017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2363fd8dd59'
down_revision = 'e1b2cec09880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'soft_prompts',
        sa.Column('id', sa.String, autoincrement=False, nullable=False),
        sa.Column('name', sa.String, autoincrement=False, nullable=False),
        sa.Column('description', sa.String, autoincrement=False, nullable=True),
        sa.Column('public', sa.Boolean, default=sa.Boolean(True), autoincrement=False, nullable=False),
        sa.Column('creator', sa.Integer, autoincrement=False, nullable=False),

        # TEMP: it doesn't seem like we actually use the models table yet
        sa.Column('model', sa.String, nullable=False),

        # in the future, this will be required
        sa.Column('model_id', sa.Integer, autoincrement=False, nullable=True),

        sa.Column('loss', sa.Numeric, autoincrement=False, nullable=False),
        sa.Column('steps', sa.Integer, autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['creator'], ['users.id'], name='fk_soft_prompts_users_id', onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['model_id'], ['models.id'], name='fk_soft_prompts_models_id', onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='pk_soft_prompts')
    )
    op.create_index('ix_soft_prompts_id', 'soft_prompts', ['id'], unique=False)
    op.create_index('ix_soft_prompts_creator', 'soft_prompts', ['creator'], unique=False)
    op.create_index('ix_soft_prompts_model_id', 'soft_prompts', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_soft_prompts_creator', table_name='soft_prompts')
    op.drop_index('ix_soft_prompts_id', table_name='soft_prompts')
    op.drop_index('ix_soft_prompts_model_id', table_name='soft_prompts')
    op.drop_table('soft_prompts')
    # ### end Alembic commands ###
