"""init

Revision ID: e1b2cec09880
Revises: 
Create Date: 2021-12-11 02:44:46.529627

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e1b2cec09880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
                    sa.Column('model_name', sa.String(), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('model_name')
                    )
    op.create_index(op.f('ix_models_model_name'), 'models', ['model_name'], unique=False)
    op.create_table('users',
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('approved', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('username')
                    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('user_model_association',
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('model_name', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['model_name'], ['models.model_name'], ),
                    sa.ForeignKeyConstraint(['username'], ['users.username'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model_association')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_models_model_name'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
