"""init

Revision ID: e1b2cec09880
Revises:
Create Date: 2021-12-11 02:44:46.529627

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1b2cec09880"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("username", sa.String, nullable=False),
        sa.Column("password", sa.String, nullable=True),
        sa.Column("email", sa.String, unique=True, nullable=False),
        sa.Column("permission_level", sa.SmallInteger, default=0, nullable=True),
    )

    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "models",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, unique=True, nullable=False),
        sa.Column("size", sa.Integer, nullable=False),
    )

    op.create_index(op.f("ix_models_id"), "models", ["id"], unique=True)
    op.create_index(op.f("ix_models_name"), "models", ["name"], unique=False)

    op.create_table(
        "user_model_association",
        sa.Column("user_id", sa.Integer, nullable=True),
        sa.Column("model_id", sa.Integer, nullable=True),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_model_association")

    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    op.drop_index(op.f("ix_models_id"), table_name="models")
    op.drop_index(op.f("ix_models_name"), table_name="models")
    op.drop_table("models")
    # ### end Alembic commands ###
